name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  windows_build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Compile
        run: |
          mkdir build
          cmake -S . -B build -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -Wno-dev
          cmake --build build --config Release --target package
      - name: 'Upload Windows Installer'
        uses: actions/upload-artifact@v4
        with:
          name: 'Windows Installer'
          path: build/_CPack_Packages/win64/NSIS/*.exe